# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carmen's Personal Website
email: vazquecm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a passionate software developer with a desire to help my community improve life through efficient and pragmatic application design. Although my time at Nashville Software School has come to an end, there is still so much more I want to learn and experiment with in the tech world.  So send me a message and we can start helping our families, friends, and neighbors not only improve their lives but make a real impact in them!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vazquecm.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  vazquecm
linkedin_username:

# Build settings
markdown: kramdown
